# Generated by Django 2.2 on 2020-07-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='ToDo_Task',
        ),
    ]
